include("${CMAKE_CURRENT_LIST_DIR}/../cmake/ShaderSourceHash.cmake")
if(NOT DEFINED OFF_TEST_WORK_DIR)
    message(FATAL_ERROR "An explicit test work directory is required")
endif()
file(MAKE_DIRECTORY "${OFF_TEST_WORK_DIR}")
file(WRITE "${OFF_TEST_WORK_DIR}/lf.frag" "first line\nsecond line\n")
file(WRITE "${OFF_TEST_WORK_DIR}/crlf.frag" "first line\r\nsecond line\r\n")
file(WRITE "${OFF_TEST_WORK_DIR}/changed.frag" "first line\nchanged second line\n")
off_shader_source_sha("${OFF_TEST_WORK_DIR}/lf.frag" lf_sha)
off_shader_source_sha("${OFF_TEST_WORK_DIR}/crlf.frag" crlf_sha)
off_shader_source_sha("${OFF_TEST_WORK_DIR}/changed.frag" changed_sha)
string(SHA256 expected_sha "first line\nsecond line\n")
if(NOT lf_sha STREQUAL expected_sha OR NOT crlf_sha STREQUAL expected_sha)
    message(FATAL_ERROR "Shader hashes must agree across LF and CRLF checkouts")
endif()
if(changed_sha STREQUAL lf_sha)
    message(FATAL_ERROR "Actual shader source edits must change the hash")
endif()
