#!/usr/bin/env python3
"""Regenerate the project-owned stage-zero shader; no game files are inputs."""

import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess
import tempfile


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--glslang", required=True)
    parser.add_argument("--spirv-cross", required=True)
    parser.add_argument("--spirv-val", required=True)
    parser.add_argument("--work-dir", type=Path, required=True,
                        help="Existing explicit directory for temporary compiler outputs")
    parser.add_argument("--check", action="store_true", help="Compare without changing the generated header")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    source = root / "assets/shaders/picture_stage.frag"
    target = root / "include/off/platform/generated/picture_stage_frag.hpp"
    if not args.work_dir.is_dir():
        parser.error("--work-dir must name an existing directory")
    build_env = os.environ.copy()
    build_env.update({key: str(args.work_dir.resolve()) for key in ("TMPDIR", "TMP", "TEMP")})
    with tempfile.TemporaryDirectory(prefix="picture-shader-", dir=args.work_dir) as scratch:
        spv = Path(scratch) / "picture.frag.spv"
        msl = Path(scratch) / "picture.frag.msl"
        subprocess.run([args.glslang, "-V", "--target-env", "vulkan1.0", "-S", "frag",
                        "-o", str(spv), str(source)], check=True, env=build_env)
        subprocess.run([args.spirv_val, "--target-env", "vulkan1.0", str(spv)], check=True, env=build_env)
        reflection = json.loads(subprocess.check_output(
            [args.spirv_cross, str(spv), "--reflect"], text=True, env=build_env))
        if reflection.get("entryPoints") != [{"name": "main", "mode": "frag"}]:
            raise RuntimeError("Unexpected shader entry point")
        inputs = sorted((item["location"], item["type"]) for item in reflection.get("inputs", []))
        outputs = [(item["location"], item["type"]) for item in reflection.get("outputs", [])]
        textures = [(item["set"], item["binding"], item["type"]) for item in reflection.get("textures", [])]
        uniforms = reflection.get("ubos", [])
        if inputs != [(0, "vec4"), (1, "vec2")] or outputs != [(0, "vec4")] or textures != [(2, 0, "sampler2D")]:
            raise RuntimeError("Unexpected SDL picture shader interface")
        if len(uniforms) != 1 or (uniforms[0]["set"], uniforms[0]["binding"], uniforms[0]["block_size"]) != (3, 0, 48):
            raise RuntimeError("Unexpected fragment uniform block")
        members = reflection["types"][uniforms[0]["type"]]["members"]
        if [(item["offset"], item["type"]) for item in members] != [(0, "uvec4"), (16, "uvec4"), (32, "vec4")]:
            raise RuntimeError("Unexpected std140 uniform member layout")
        subprocess.run([args.spirv_cross, str(spv), "--msl", "--msl-version", "20100",
                        "--output", str(msl)], check=True, env=build_env)
        bytecode = spv.read_bytes()
        metal = msl.read_text(encoding="utf-8")
        # Bindings must match SDL's fragment sampler/uniform slots.
        for binding in ("[[buffer(0)]]", "[[texture(0)]]", "[[sampler(0)]]"):
            if binding not in metal:
                raise RuntimeError(f"Unexpected Metal resource layout: missing {binding}")
        if ')OFF_MSL"' in metal:
            raise RuntimeError("Generated Metal source collides with C++ literal delimiter")
        lines = [", ".join(f"0x{b:02x}" for b in bytecode[i:i + 16]) for i in range(0, len(bytecode), 16)]
        output = "// Generated by tools/build_picture_shader.py; do not edit.\n"
        output += f"// GLSL SHA256: {hashlib.sha256(source.read_bytes()).hexdigest()}\n"
        output += "#pragma once\n\nnamespace off::platform::generated {\n"
        output += "alignas(4) inline constexpr unsigned char picture_stage_spirv[] = {\n  "
        output += ",\n  ".join(lines) + "\n};\n"
        output += 'inline constexpr char picture_stage_msl[] = R"OFF_MSL(' + metal + ')OFF_MSL";\n'
        output += "} // namespace off::platform::generated\n"
        if args.check:
            if not target.is_file() or target.read_text(encoding="utf-8") != output:
                raise SystemExit("Generated picture shader is stale or compiler output differs")
            print("Generated picture shader matches source and tool output")
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(output, encoding="utf-8")
            print(f"Generated {target.name}: {len(bytecode)} SPIR-V bytes and {len(metal)} MSL characters")


if __name__ == "__main__":
    main()
