#!/usr/bin/env python3
"""Compile the project-owned generated HLSL into a portable embedded DXIL header."""

import argparse
import hashlib
import os
from pathlib import Path
import struct
import subprocess
import tempfile


def validate_container(blob):
    if len(blob) < 32 or blob[:4] != b"DXBC":
        raise RuntimeError("DXC did not produce a shader container")
    size, count = struct.unpack_from("<II", blob, 24)
    if size != len(blob) or count > (len(blob) - 32) // 4:
        raise RuntimeError("Invalid shader container bounds")
    found_dxil = False
    for index in range(count):
        offset = struct.unpack_from("<I", blob, 32 + index * 4)[0]
        if offset < 32 + count * 4 or offset > len(blob) - 8:
            raise RuntimeError("Invalid shader chunk offset")
        chunk_size = struct.unpack_from("<I", blob, offset + 4)[0]
        if chunk_size > len(blob) - offset - 8:
            raise RuntimeError("Invalid shader chunk size")
        found_dxil |= blob[offset:offset + 4] == b"DXIL"
    if not found_dxil:
        raise RuntimeError("Shader container has no DXIL program")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dxc", required=True)
    parser.add_argument("--work-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if not args.work_dir.is_dir():
        parser.error("--work-dir must name an existing directory")
    root = Path(__file__).resolve().parents[1]
    source = root / "assets/shaders/generated/picture_stage.frag.hlsl"
    target = args.output or root / "include/off/platform/generated/picture_stage_dxil.hpp"
    build_env = os.environ.copy()
    build_env.update({key: str(args.work_dir.resolve()) for key in ("TMPDIR", "TMP", "TEMP")})
    with tempfile.TemporaryDirectory(prefix="picture-dxil-", dir=args.work_dir) as scratch:
        binary = Path(scratch) / "picture.frag.dxil"
        subprocess.run([args.dxc, "-T", "ps_6_0", "-E", "main", "-HV", "2021", "-O3",
                        "-Ges", "-WX", "-Fo", str(binary), str(source)], check=True, env=build_env)
        # DXC compilation includes validation; dump reflection/IR into the CI log
        # so register spaces, signatures and shader model remain reviewable.
        subprocess.run([args.dxc, "-dumpbin", str(binary)], check=True, env=build_env)
        blob = binary.read_bytes()
        validate_container(blob)
        rows = [", ".join(f"0x{b:02x}" for b in blob[i:i + 16]) for i in range(0, len(blob), 16)]
        output = "// Generated by tools/build_picture_dxil.py; do not edit.\n"
        output += f"// HLSL SHA256: {hashlib.sha256(source.read_text(encoding='utf-8').encode('utf-8')).hexdigest()}\n"
        output += "#pragma once\n\nnamespace off::platform::generated {\n"
        output += "alignas(4) inline constexpr unsigned char picture_stage_dxil[] = {\n  "
        output += ",\n  ".join(rows) + "\n};\n} // namespace off::platform::generated\n"
        if args.check:
            if not target.is_file() or target.read_text(encoding="utf-8") != output:
                raise SystemExit("Generated DXIL header is stale or compiler output differs")
            print("Generated DXIL header matches source and compiler output")
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(output, encoding="utf-8")
            print(f"Generated {target.name}: {len(blob)} DXIL container bytes")


if __name__ == "__main__":
    main()
